version: '3.8'
services:
  frontend:
    environment:
      - NODE_ENV=development
    ports:
      - "4200:4200"  # Porta do Angular dev server
  
  nginx:
    environment:
      - HOSTNAME=dev.interacoes.ifce.edu.br
    ports:
      - "4000:80"
