name: Deploy Develop Environment

on:
  repository_dispatch:
    types: [frontend-updated]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Verificar se o evento foi acionado pela branch develop
      - name: Check if develop branch
        id: check-branch
        run: |
          if [ "${{ github.event.client_payload.branch }}" != "develop" ]; then
            echo "This event is not for the develop branch. Exiting."
            exit 78  # Exit with a neutral status to skip the workflow
          fi

      # Checkout da branch develop
      - name: Checkout Containers repository
        uses: actions/checkout@v3
        with:
          ref: develop
          submodules: 'recursive'

      # Atualizar o submódulo do frontend para a branch develop
      - name: Update frontend submodule
        run: |
          cd frontend || exit 1
          git fetch --all || exit 1
          git checkout develop || exit 1
          git pull origin develop || exit 1

      # Deploy no servidor
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/develop || exit 1
            git pull origin develop || exit 1
            git submodule update --init --recursive || exit 1
            docker-compose -f docker-compose.yml -f docker-compose.develop.yml up -d --build