name: Deploy Test Environment

on:
  repository_dispatch:
    types: [frontend-test]

jobs:
  deploy:
    if: github.event.client_payload.branch == 'test'  # Condição para executar apenas se a branch for test
    runs-on: ubuntu-latest

    steps:
      # Verificar se o evento foi acionado pela branch test
      - name: Check if test branch
        id: check-branch
        run: |
          if [ "${{ github.event.client_payload.branch }}" != "test" ]; then
            echo "This event is not for the test branch. Exiting."
            exit 78  # Exit with a neutral status to skip the workflow
          fi

      # Checkout da branch test
      - name: Checkout Containers repository
        uses: actions/checkout@v3
        with:
          ref: test
          submodules: 'recursive'

      # Atualizar o submódulo do frontend para a branch test
      - name: Update frontend submodule
        run: |
          cd frontend || exit 1
          git fetch --all || exit 1
          git checkout test || exit 1
          git pull origin test || exit 1

      # Deploy no servidor
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/test || exit 1
            git pull origin test || exit 1
            git submodule update --init --recursive || exit 1
            docker-compose -f docker-compose.yml -f docker-compose.teste.yml up -d --build
