name: Deploy Production Environment

on:
  repository_dispatch:
    types: [frontend-main]

jobs:
  deploy:
    if: github.event.client_payload.branch == 'main'  
    runs-on: ubuntu-latest

    steps:
      # Checkout da branch main
      - name: Checkout Containers repository
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: 'recursive'

      # Atualizar o submódulo do frontend para a branch main
      - name: Update frontend submodule
        run: |
          cd frontend || exit 1
          git fetch --all || exit 1
          git checkout main || exit 1
          git pull origin main || exit 1

      # Deploy no servidor
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/production || exit 1
            git pull origin main || exit 1
            git submodule update --init --recursive || exit 1
            docker-compose up -d --build
